[virtual_workspaces]
enabled = true
default_workspace_count = 6
auto_assign_windows = true
preserve_focus_per_workspace = true
workspace_auto_back_and_forth = false
reapply_app_rules_on_title_change = false

workspace_names = [
	"1",
	"2",
	"3",
	"4",
	"􀖇",
	"􀫀"
]

workspace_rules = [
  { workspace = "1", layout = "bsp" },
  { workspace = "2", layout = "scrolling" },
  { workspace = "3", layout = "master_stack" },
  { workspace = "4", layout = "master_stack" },
  { workspace = "􀖇", layout = "scrolling" },
  { workspace = "􀫀", layout = "scrolling" }
]

default_workspace = 2

app_rules = [
  { app_id = "com.apple.systempreferences", floating = true },
  { app_id = "com.ugreen.pro.client", floating = true },
  { app_id = "com.spotify.client", workspace = 5 }
]

[settings]
animate = true
animation_duration = 0.3
animation_fps = 120.0

default_disable = false

focus_follows_mouse = false
mouse_follows_focus = true
mouse_hides_on_focus = false

hot_reload = true
run_on_start = ["sketchybar --reload"]

[settings.layout.master_stack]
master_ratio = 0.9
master_count = 2
master_side = "left"
new_window_placement = "master"
master_arrangement = "horizontal"
stack_arrangement = "vertical"

[settings.layout.scrolling]
column_width_ratio = 0.9
min_column_width_ratio = 0.1
max_column_width_ratio = 0.9
focus_navigation_style = "niri"
animate=false

[settings.layout.gaps.outer]
top=5
left = 5
bottom = 5
right = 5

[settings.layout.gaps.inner]
horizontal = 10
vertical = 10

[settings.ui.menu_bar]
enabled = true
show_empty = false
mode = "all"
active_label = "index"
display_style = "layout"

[settings.ui.stack_line]
enabled = false
horiz_placement = "top"
vert_placement = "left"
thickness = 20.0
spacing = 1.0

[settings.ui.mission_control]
enabled = false
fade_enabled = false
fade_duration_ms = 180.0

[settings.gestures]
enabled = true
invert_horizontal_swipe = false
swipe_vertical_tolerance = 0.4
skip_empty = true
fingers = 3
distance_pct = 0.08
haptics_enabled = false
haptic_pattern = "level_change"

[settings.window_snapping]
drag_swap_fraction = 0.3


[modifier_combinations]
aeromod = "Ctrl + Alt + Meta"
aeroshift = "Ctrl + Alt + Meta + Shift"

[keys]
# Focus
"aeromod + Q" = { move_focus = "left" }
"aeromod + W" = { move_focus = "down" }
"aeromod + E" = { move_focus = "up" }
"aeromod + R" = { move_focus = "right" }

# Move nodes
"aeromod + J" = { move_node = "left" }
"aeromod + K" = { move_node = "down" }
"aeromod + L" = { move_node = "up" }
"aeromod + Semicolon" = { move_node = "right" }

# Workspaces
"aeromod + 1" = { switch_to_workspace = 0 }
"aeromod + 2" = { switch_to_workspace = 1 }
"aeromod + 3" = { switch_to_workspace = 2 }
"aeromod + 4" = { switch_to_workspace = 3 }
"aeromod + 5" = { switch_to_workspace = 4 }

"aeroshift + 1" = { move_window_to_workspace = 0 }
"aeroshift + 2" = { move_window_to_workspace = 1 }
"aeroshift + 3" = { move_window_to_workspace = 2 }
"aeroshift + 4" = { move_window_to_workspace = 3 }
"aeroshift + 5" = { move_window_to_workspace = 4 }


# Sizing and Window states
"aeromod + A" = "resize_window_shrink"
"aeromod + S" = "resize_window_grow"
"aeromod + F" = "toggle_window_floating"

# Defaults
"Ctrl + Enter" = { "exec" = ["open_or_pull", "Zen", "app.zen-browser.zen"] }
"Ctrl + Shift + Enter" = { "exec" = ["open_or_pull", "Antigravity IDE", "com.google.antigravity"] }
